myaudit/routes/mission.py
from myaudit import db, login_manager


from myaudit.models import Missions, MissionDroits, Domaines, Themes, Chapitres, Questions, QuestionsCache, MissionReponse, RecommandationsAudit
from myaudit.forms import MissionForm, QuestionnaireForm, AddUserToMissionForm
from myaudit.utils import log_action, check_permissions

from sqlalchemy import or_

from werkzeug.utils import secure_filename

from flask import current_app, Blueprint, flash, redirect, render_template, request, url_for
from flask_login import current_user, login_user, logout_user, login_required

import datetime, os

mission = Blueprint('mission', __name__)

@mission.route('/missions', methods=['GET', 'POST'])
@log_action
@login_required
def missions():
        missions = Missions.query.join(MissionDroits).filter(MissionDroits.id_user == current_user.id_user, MissionDroits.droit.in_(['chef de projet', 'auditeur'])).all()
        return render_template('missions.html', missions=missions)

@mission.route('/create_mission', methods=['GET', 'POST'])
@log_action
@login_required
def create_mission():
    form = MissionForm()
    domaines = Domaines.query.all()
    choices = []
    themes_dict = {}

    for domaine in domaines:
        theme = Themes.query.get(domaine.id_theme)
        if theme.id_theme not in themes_dict:
            themes_dict[theme.id_theme] = theme.theme
        choices.append((domaine.id_domaine, f"{theme.theme} - {domaine.domaine}"))

    form.id_domaine.choices = choices

    if form.validate_on_submit():
        mission = Missions(
            id_domaine=form.id_domaine.data,
            mission=form.mission.data,
            client_name=form.client_name.data,
            client_company=form.client_company.data,
            client_address=form.client_address.data,
            client_siren=form.client_siren.data,
            client_produit=form.client_produit.data,
            client_representative=form.client_representative.data,
            client_title=form.client_title.data,
            date_création=datetime.date.today(),
            date_planification=form.date_planification.data,
            date_presentation=form.date_presentation.data,
            date_restitutation=form.date_restitutation.data,
            date_debut_mission=form.date_debut_mission.data,
            date_fin_mission=form.date_fin_mission.data,
            date_debut_audit=form.date_debut_audit.data,
            date_fin_audit=form.date_fin_audit.data,
            date_rapport=form.date_rapport.data,
            date_lastUpdate=datetime.date.today()
        )
        try:
            db.session.add(mission)
            db.session.flush()
        except:
            return render_template('erreur.html', erreur="Erreur dans la création d'une mission")
        mission_droit = MissionDroits(
            id_mission=mission.id_mission,
            id_user=current_user.id_user,
            droit='chef de projet'
        )

        db.session.add(mission_droit)
        db.session.commit()

        flash('Mission created successfully!', 'success')
        return redirect(url_for('mission.missions'))

    return render_template('create_mission.html', title='Nouvelle mission', form=form)

@mission.route('/edit_mission/<int:id_mission>', methods=['GET', 'POST'])
@log_action
@login_required
@check_permissions(lambda id_mission: id_mission, required_roles=['chef de projet'])
def edit_mission(id_mission):
    mission = Missions.query.get_or_404(id_mission)
    form = MissionForm()
    domaines = Domaines.query.all()
    choices = []
    themes_dict = {}

    for domaine in domaines:
        theme = Themes.query.get(domaine.id_theme)
        if theme.id_theme not in themes_dict:
            themes_dict[theme.id_theme] = theme.theme
        choices.append((domaine.id_domaine, f"{theme.theme} - {domaine.domaine}"))

    form.id_domaine.choices = choices

    if form.validate_on_submit():
        mission.id_domaine = form.id_domaine.data
        mission.mission = form.mission.data
        mission.client_name = form.client_name.data
        mission.client_company = form.client_company.data
        mission.client_address = form.client_address.data
        mission.client_siren = form.client_siren.data
        mission.client_produit = form.client_produit.data
        mission.client_representative = form.client_representative.data
        mission.client_title = form.client_title.data
        mission.date_planification = form.date_planification.data
        mission.date_presentation = form.date_presentation.data
        mission.date_restitutation = form.date_restitutation.data
        mission.date_debut_mission = form.date_debut_mission.data
        mission.date_fin_mission = form.date_fin_mission.data
        mission.date_debut_audit = form.date_debut_audit.data
        mission.date_fin_audit = form.date_fin_audit.data
        mission.date_rapport = form.date_rapport.data
        mission.date_lastUpdate = datetime.date.today()
        db.session.add(mission)
        db.session.commit()
        flash('Domaine updated successfully', 'success')
        return redirect(url_for('mission.missions'))
    elif request.method == 'GET':
        form.mission.data = mission.mission
        form.client_name.data = mission.client_name
        form.client_company.data = mission.client_company
        form.client_address.data = str(mission.client_address)
        form.client_siren.data = str(mission.client_siren)
        form.client_produit.data = str(mission.client_produit)
        form.client_representative.data = str(mission.client_representative)
        form.client_title.data = str(mission.client_title)
        form.date_planification.data = mission.date_planification
        form.date_presentation.data = mission.date_presentation
        form.date_restitutation.data = mission.date_restitutation
        form.date_debut_mission.data = mission.date_debut_mission
        form.date_fin_mission.data = mission.date_fin_mission
        form.date_debut_audit.data = mission.date_debut_audit
        form.date_fin_audit.data = mission.date_fin_audit
        form.date_rapport.data = mission.date_rapport
    
    return render_template('edit_mission.html', title='Edition de la misson {{mission.client_name}}', form=form)

@mission.route('/edit_right/<int:id_mission>', methods=['GET', 'POST'])
@log_action
@login_required
@check_permissions(lambda id_mission: id_mission, required_roles=['chef de projet'])
def edit_right(id_mission):
    mission = Missions.query.get_or_404(id_mission)
    form = AddUserToMissionForm()
    if form.validate_on_submit():
        user_id = form.user.data
        role = form.role.data
        existing_entry = MissionDroits.query.filter_by(id_mission=id_mission, id_user=user_id).first()
        if existing_entry:
            existing_entry.droit = role
            flash('Cet utilisateur a déjà été ajouté à cette mission.', 'danger')
        else:
            new_entry = MissionDroits(id_mission=id_mission, id_user=user_id, droit=role)
            db.session.add(new_entry)
        db.session.commit()
        flash('Utilisateur ajouté avec succès à la mission.', 'success')
        return redirect(url_for('mission.missions', id_mission=id_mission))
    return render_template('edit_right.html', form=form, mission=mission)


@mission.route('/travail/<int:id_mission>', methods=['GET'])
@log_action
@login_required
@check_permissions(lambda id_mission: id_mission, required_roles=['chef de projet', 'auditeur'])
def travail(id_mission):
    if not QuestionsCache.query.filter_by(id_mission=id_mission).all():
        update_question_cache(id_mission)
    questions = QuestionsCache.query.filter_by(id_mission=id_mission).all()
    questions_list = [question.to_dict() for question in questions]
    return render_template('travail.html', title='Questions à réaliser', questions_list=questions_list)


#region Questionnaire
@mission.route('/questionnaire/<int:id_mission>/<int:id_question>', methods=['GET', 'POST'])
@log_action
@login_required
@check_permissions(lambda id_mission, id_question: id_mission, required_roles=['chef de projet', 'auditeur'])
def questionnaire(id_mission, id_question):
    questioncache = QuestionsCache.query.filter_by(id_mission=id_mission,id_question=id_question).first()
    recommandations_audit_list = RecommandationsAudit.query.filter_by(id_questionsCache=questioncache.id_questionsCache).all()
    recommandations_audit_dicts = [ra.to_dict() for ra in recommandations_audit_list]

    if request.method == 'POST':
        OLD_id_question = id_question - 1
        reponse = MissionReponse.query.filter_by(id_mission=id_mission, id_question=OLD_id_question).first()    
        question = QuestionsCache.query.filter_by(id_mission=id_mission, id_question=OLD_id_question).first()
        form = QuestionnaireForm(obj=reponse)

        if not question:
            flash('Question not found', 'danger')
            return redirect(url_for('menu.dashboard'))
        
        if form.validate_on_submit():
            filename = None
            if form.piece_jointe.data:
                filename = secure_filename(form.piece_jointe.data.filename)
                upload_folder = current_app.config['UPLOAD_FOLDER']
                form.piece_jointe.data.save(os.path.join(upload_folder, filename))
            
            
            if reponse:
                reponse.reponse = form.reponse.data
                reponse.evaluation = form.evaluation.data
                reponse.piece_jointe = filename
            else:
                reponse = MissionReponse(
                    id_mission=id_mission,
                    id_question=OLD_id_question, # Envoie les données de la question précédente
                    id_user=current_user.id_user,
                    reponse=form.reponse.data,
                    evaluation=form.evaluation.data,
                    piece_jointe=filename
                )
                db.session.add(reponse)
            db.session.commit()

myaudit/routes/profils.py
from flask import Blueprint, render_template, redirect, url_for, flash, request
from flask_login import login_required, current_user
from werkzeug.security import generate_password_hash
from myaudit import db
from myaudit.models import Users, Logs
from myaudit.utils import log_action

from argon2 import PasswordHasher
from argon2.exceptions import VerifyMismatchError

profils = Blueprint('profils', __name__)
ph = PasswordHasher()

@profils.route('/profil', methods=['GET', 'POST'])
@log_action
@login_required
def profil():
    if request.method == 'POST':
        current_user.username = request.form.get('username')
        new_password = request.form.get('password')
        if new_password:
            hashed_password = ph.hash(new_password)
            current_user.password = hashed_password 
        try:
            db.session.commit()
        except:
            return render_template('erreur.html', erreur="Problème de changement d'utilisateur ou mot de passe")
        flash('Votre profil a été mis à jour.', 'success')
        return redirect(url_for('profils.profil'))

    return render_template('profil.html', title='Mon Profil', user=current_user)


@profils.route('/admin/users', methods=['GET', 'POST'])
@log_action
@login_required
def manage_users():
    if not current_user.is_admin():
        flash('Accès refusé.', 'danger')
        return redirect(url_for('profils.profil'))

    users = Users.query.all()

    if request.method == 'POST':
        user_id = request.form.get('user_id')
        action = request.form.get('action')  
        user = Users.query.get(user_id)
        
        if user:
            if action == 'promote':
                if user.droits_generaux != 'admin':  
                    user.droits_generaux = 'admin'
                    db.session.commit()
                    flash(f"L'utilisateur {user.username} a été promu administrateur.", 'success')
                else:
                    flash(f"L'utilisateur {user.username} est déjà administrateur.", 'warning')
            elif action == 'demote':
                if user.droits_generaux == 'admin':  
                    user.droits_generaux = None  
                    db.session.commit()
                    flash(f"L'utilisateur {user.username} a été rétrogradé.", 'success')
                else:
                    flash(f"L'utilisateur {user.username} n'est pas administrateur.", 'warning')
            elif action == 'delete':
                db.session.delete(user)
                db.session.commit()
                flash(f"L'utilisateur {user.username} a été supprimé.", 'success')
        else:
            flash("Utilisateur non trouvé.", 'danger')

        return redirect(url_for('profils.manage_users'))

    return render_template('manage_users.html', title='Gestion des utilisateurs', users=users)


@profils.route('/logs', methods=['GET', 'POST'])
@log_action
@login_required
def logs():
    logs = Logs.query.all()
    return render_template('logs.html', title='Mon Profil', logs=logs)

myaudit/templates/html/base.html
<!DOCTYPE html>
<html lang="fr">
<head>
    <!-- v0.1.0 -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Votre Titre{% endblock %}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
</head>
<body>
    <header>
        {% if current_user.is_authenticated %}<a href="/dashboard"class="logo">Dashboard</a>        {% endif %}
        {% if current_user.is_authenticated %}<a href="/profil">Profil</a>        {% endif %}
        {% if current_user.is_authenticated %}<a href="/missions">Missions</a>        {% endif %}
        {% if current_user.is_authenticated %}<a href="/paramétrages">Configuration de la plateforme</a>        {% endif %}
        {% if current_user.is_authenticated %}<a href="/logout">Déconnexion</a>{% else %}<a href="/login">Connexion</a>{% endif %}
    </header>

    <main>
        {% block content %}
        <!-- Contenu spécifique à chaque page va ici -->
        {% endblock %}
    </main>
</body>
</html>

myaudit/templates/html/create_domaine.html
{% extends "base.html" %}
{% block content %}
<div class="form-container active">
    <h2 class="mb-4">{{ title }}</h2>
    <form method="POST">
        {{ form.hidden_tag() }}
        <div class="form-group">
            {{ form.id_theme.label(class="form-label") }}
            {{ form.id_theme(class="form-control", id='id_theme') }}
        </div>
        <div class="form-group">
            {{ form.domaine.label(class="form-label") }}
            {{ form.domaine(class="form-control") }}
        </div>
        <div class="form-group">
            {{ form.submit(class="btn btn-primary") }}
        </div>
    </form>
</div>
{% endblock %}

myaudit/templates/html/create_mission.html
{% extends "base.html" %}
{% block content %}
<div class="body"></div>
    <h2>{{ title }}</h2>
    <div class="container">
        <form method="POST">
            {{ form.hidden_tag() }}
            <div class="form-group">
                {{ form.id_domaine.label(class="form-label") }}
                {{ form.id_domaine(class="form-control") }}
            </div>
            <div class="form-group">
                {{ form.mission.label(class="form-label") }}
                {{ form.mission(class="form-control") }}
            </div>
            <div class="form-group">
                {{ form.client_name.label(class="form-label") }}
                {{ form.client_name(class="form-control") }}
            </div>
            <div class="form-group">
                {{ form.client_company.label(class="form-label") }}
                {{ form.client_company(class="form-control") }}
            </div>
            <div class="form-group">
                {{ form.client_address.label(class="form-label") }}
                {{ form.client_address(class="form-control") }}
            </div>
            <div class="form-group">
                {{ form.client_siren.label(class="form-label") }}
                {{ form.client_siren(class="form-control") }}
            </div>
            <div class="form-group">
                {{ form.client_produit.label(class="form-label") }}
                {{ form.client_produit(class="form-control") }}
            </div>
            <div class="form-group">
                {{ form.client_representative.label(class="form-label") }}
                {{ form.client_representative(class="form-control") }}
            </div><div class="form-group">
                {{ form.client_title.label(class="form-label") }}
                {{ form.client_title(class="form-control") }}
            </div>
            <div class="form-group">
                {{ form.date_planification.label(class="form-label") }}
                {{ form.date_planification(class="form-control") }}
            </div>  
            <div class="form-group">
                {{ form.date_presentation.label(class="form-label") }}
                {{ form.date_presentation(class="form-control") }}
            </div>  
            <div class="form-group">
                {{ form.date_restitutation.label(class="form-label") }}
                {{ form.date_restitutation(class="form-control") }}
            </div>  
            <div class="form-group">
                {{ form.date_debut_mission.label(class="form-label") }}
                {{ form.date_debut_mission(class="form-control") }}
            </div>  
            <div class="form-group">
                {{ form.date_fin_mission.label(class="form-label") }}
                {{ form.date_fin_mission(class="form-control") }}
            </div>  
            <div class="form-group">
                {{ form.date_debut_audit.label(class="form-label") }}
                {{ form.date_debut_audit(class="form-control") }}
            </div>  
            <div class="form-group">
                {{ form.date_fin_audit.label(class="form-label") }}
                {{ form.date_fin_audit(class="form-control") }}
            </div>  
            <div class="form-group">
                {{ form.date_rapport.label(class="form-label") }}
                {{ form.date_rapport(class="form-control") }}
            </div>  
            
            <div class="form-group">
                {{ form.submit(class="btn btn-primary") }}
            </div>
        </form>
    </div>
</div>
{% endblock %}

myaudit/templates/html/create_recommandation.html
{% extends "base.html" %}
{% block content %}
<div class="form-container active">
    <h2 class="mb-4">{{ title }}</h2>
    <form method="POST">
        {{ form.hidden_tag() }}
        <div class="form-group">
            {{ form.titre_reco.label(class="form-label") }}
            {{ form.titre_reco(class="form-control") }}
        </div>
         <div class="form-group">
            {{ form.recommandation.label(class="form-label") }}
            {{ form.recommandation(class="form-control") }}
        </div>
         <div class="form-group">
            {{ form.titre_vuln.label(class="form-label") }}
            {{ form.titre_vuln(class="form-control") }}
        </div>
         <div class="form-group">
            {{ form.vuln.label(class="form-label") }}
            {{ form.vuln(class="form-control") }}
        </div>
         <div class="form-group">
            {{ form.v_impact.label(class="form-label") }}
            {{ form.v_impact(class="form-control") }}
        </div>
         <div class="form-group">
            {{ form.v_proba.label(class="form-label") }}
            {{ form.v_proba(class="form-control") }}
        </div>
        <div class="form-group">
            {{ form.submit(class="btn btn-primary") }}
        </div>
    </form>
</div>
{% endblock %}

myaudit/templates/html/create_theme.html
{% extends "base.html" %}
{% block content %}
<div class="form-container active">
    <h2 class="mb-4">{{ title }}</h2>
    <form method="POST">
        {{ form.hidden_tag() }}
        <div class="form-group">
            {{ form.theme.label(class="form-label") }}
            {{ form.theme(class="form-control") }}
        </div>
        <div class="form-group">
            {{ form.submit(class="btn btn-primary") }}
        </div>
    </form>
</div>
{% endblock %}

myaudit/templates/html/edit_domaine.html
{% extends "base.html" %}

{% block content %}
<div class="form-container active">
    <h2>{{ title }}</h2>
    <form method="POST">
        {{ form.hidden_tag() }}
        <div class="form-group">
            {{ form.id_theme.label(class="form-label") }}
            {{ form.id_theme(class="form-control") }}
        </div>
        <div class="form-group">
            {{ form.texte.label(class="form-label") }}
            {{ form.texte(class="form-control") }}
        </div>
        <div class="form-group">
            {{ form.submit(class="btn btn-primary") }}
        </div>
    </form>
</div>
{% endblock %}

myaudit/templates/html/edit_mission.html
{% extends "base.html" %}

{% block content %}
<div class="form-container active">
    <h2>{{ title }}</h2>
    <form method="POST">
        {{ form.hidden_tag() }}
        <div class="form-group">
            {{ form.id_domaine.label(class="form-label") }}
            {{ form.id_domaine(class="form-control") }}
        </div>
        <div class="form-group">
            {{ form.mission.label(class="form-label") }}
            {{ form.mission(class="form-control") }}
        </div>
        <div class="form-group">
            {{ form.client_name.label(class="form-label") }}
            {{ form.client_name(class="form-control") }}
        </div>
        <div class="form-group">
            {{ form.client_company.label(class="form-label") }}
            {{ form.client_company(class="form-control") }}
        </div>
        <div class="form-group">
            {{ form.client_address.label(class="form-label") }}
            {{ form.client_address(class="form-control") }}
        </div>
        <div class="form-group">
            {{ form.client_siren.label(class="form-label") }}
            {{ form.client_siren(class="form-control") }}
        </div>
        <div class="form-group">
            {{ form.client_produit.label(class="form-label") }}
            {{ form.client_produit(class="form-control") }}
        </div>
        <div class="form-group">
            {{ form.client_representative.label(class="form-label") }}
            {{ form.client_representative(class="form-control") }}
        </div>
        <div class="form-group">
            {{ form.client_title.label(class="form-label") }}
            {{ form.client_title(class="form-control") }}
        </div>
        <div class="form-group">
            {{ form.date_planification.label(class="form-label") }}
            {{ form.date_planification(class="form-control") }}
        </div>
        <div class="form-group">
            {{ form.date_presentation.label(class="form-label") }}
            {{ form.date_presentation(class="form-control") }}
        </div>
        <div class="form-group">
            {{ form.date_restitutation.label(class="form-label") }}
            {{ form.date_restitutation(class="form-control") }}
        </div>
        <div class="form-group">
            {{ form.date_debut_mission.label(class="form-label") }}
            {{ form.date_debut_mission(class="form-control") }}
        </div>
        <div class="form-group">
            {{ form.date_fin_mission.label(class="form-label") }}
            {{ form.date_fin_mission(class="form-control") }}
        </div>
        <div class="form-group">
            {{ form.date_debut_audit.label(class="form-label") }}
            {{ form.date_debut_audit(class="form-control") }}
        </div>
        <div class="form-group">
            {{ form.date_fin_audit.label(class="form-label") }}
            {{ form.date_fin_audit(class="form-control") }}
        </div>
        <div class="form-group">
            {{ form.date_rapport.label(class="form-label") }}
            {{ form.date_rapport(class="form-control") }}
        </div>

        <div class="form-group">
            {{ form.submit(class="btn btn-primary") }}
        </div>
    </form>
</div>
{% endblock %}

myaudit/templates/html/edit_right.html
{% extends "base.html" %}

{% block content %}
<h2>Ajouter un utilisateur à la mission {{ mission.nom }}</h2>
<form method="POST" action="{{ url_for('mission.edit_right', id_mission=mission.id_mission) }}">
    {{ form.hidden_tag() }}
    <div class="form-group">
        {{ form.user.label(class="form-label") }}
        {{ form.user(class="form-control") }}
    </div>
    <div class="form-group">
        {{ form.role.label(class="form-label") }}
        {{ form.role(class="form-control") }}
    </div>
    <div class="form-group">
        {{ form.submit(class="btn btn-primary") }}
    </div>
</form>
{% endblock %}

myaudit/templates/html/edit_theme.html
{% extends "base.html" %}

{% block content %}
<div class="form-container active">
    <h2>{{ title }}</h2>
    <form method="POST">
        {{ form.hidden_tag() }}
        <div class="form-group">
            {{ form.theme.label(class="form-label") }}
            {{ form.theme(class="form-control") }}
        </div>
        <div class="form-group">
            {{ form.submit(class="btn btn-primary") }}
        </div>
    </form>
</div>
{% endblock %}

myaudit/templates/html/liste_chapitres.html
{% extends "base.html" %}

{% block content %}
<div class="form-container active">
    <h2>{{ title }}</h2>
    <div id="themes-container"></div>
</div>

<script>
    document.addEventListener("DOMContentLoaded", function() {
        fetch('/api/themes')
            .then(response => response.json())
            .then(themes => {
                const themesContainer = document.getElementById('themes-container');
                themes.forEach(theme => {
                    const themeElement = document.createElement('div');
                    themeElement.innerHTML = `<h3>${theme.theme}</h3><ul class="list_domaines" id="domaines-${theme.id_theme}"></ul>`;
                    themesContainer.appendChild(themeElement);

                    fetch(`/api/domaine/${theme.id_theme}`)
                        .then(response => response.json())
                        .then(domaines => {
                            const domainesList = document.getElementById(`domaines-${theme.id_theme}`);
                            domaines.forEach(domaine => {
                                const domaineElement = document.createElement('li');
                                domaineElement.innerHTML = `<strong>${domaine.domaine}</strong><ul class="list_chapitres" id="chapitres-${domaine.id_domaine}"></ul>`;
                                domainesList.appendChild(domaineElement);

                                fetch(`/api/chapitre/${domaine.id_domaine}`)
                                    .then(response => response.json())
                                    .then(chapitres => {
                                        const chapitresList = document.getElementById(`chapitres-${domaine.id_domaine}`);
                                        chapitres.forEach(chapitre => {
                                            const chapitreItem = document.createElement('li');
                                            chapitreItem.textContent = chapitre.chapitre;
                                            chapitresList.appendChild(chapitreItem);
                                        });
                                    })
                                    .catch(error => console.error('Error fetching chapitres:', error));
                            });
                        })
                        .catch(error => console.error('Error fetching domaines:', error));
                });
            })
            .catch(error => console.error('Error fetching themes:', error));
    });
</script>
{% endblock %}

myaudit/templates/html/liste_recommendations.html
{% extends "base.html" %}

{% block content %}
</br>
<div class="form-container active">
    <h2>{{ title }}</h2>
    <table id="recommendations-table">
        <thead>
            <tr>
                <th>ID</th>
                <th>Livrable</th>
                <th >Recommendations</th>
                <th>Vulnérabilités</th>
            </tr>
        </thead>
        <tbody>
            <!-- Les recommendations seront insérés ici -->
        </tbody>
    </table>

    <script>
        document.addEventListener("DOMContentLoaded", function() {
            fetch('/api/recommendations')
                .then(response => response.json())
                .then(data => {
                    const tableBody = document.querySelector('#recommendations-table tbody');
                    data.forEach(recommendation => {
                        const row = document.createElement('tr');
                        const idCell = document.createElement('td');
                        const livrablesCell = document.createElement('td');
                        const titre_recoCell = document.createElement('td');
                        const titre_vulnCell = document.createElement('td');
                        idCell.textContent = recommendation.id_recommendation;
                        livrablesCell.textContent = recommendation.livrables;
                        titre_recoCell.textContent = recommendation.titre_reco;
                        titre_vulnCell.textContent = recommendation.titre_vuln;
                        row.appendChild(idCell);
                        row.appendChild(livrablesCell);
                        row.appendChild(titre_recoCell);
                        row.appendChild(titre_vulnCell);
                        tableBody.appendChild(row);
                    });
                })
                .catch(error => console.error('Error fetching recommendations:', error));
        });
    </script>




</div>
{% endblock %}

myaudit/templates/html/profil.html
{% extends "base.html" %}

{% block content %}
<h2>Mon Profil</h2>
<form method="POST">
    <div class="form-group">
        <label for="username">Nom d'utilisateur</label>
        <input type="text" id="username" name="username" class="form-control" value="{{ user.username }}" required>
    </div>
    <div class="form-group">
        <label for="password">Nouveau mot de passe</label>
        <input type="password" id="password" name="password" class="form-control">
        <small class="form-text text-muted">Laissez vide si vous ne souhaitez pas changer le mot de passe.</small>
    </div>
    <button type="submit" class="btn btn-primary">Mettre à jour</button>
</form>

{% if user.is_admin() %}
    <hr>
    <a href="{{ url_for('profils.manage_users') }}" class="btn btn-secondary">Gérer les utilisateurs</a> <a href="{{ url_for('profils.manage_users') }}" class="btn btn-secondary">Gérer la plateforme</a> <a href="{{ url_for('profils.logs') }}" class="btn btn-secondary">Afficher les logs</a>
{% endif %}
{% endblock %}